### ISSUE TITLE
psycopg2.errors.ForeignKeyViolation when importing FIFA19 CareerSaveFile

### ISSUE THREAD

**Issue by qhash1** [xAranaktu/FIFA-Tracker#9]
Hey Aranaktu,

I'm currently trying to get your FIFA-Tracker working on an Ubuntu Server (18.04 LTS) VirtualBox.

As of now I was able to get the PostgreSQL Server and the Python Django Enviroment thingy to work but I'm running into errors when I'm processing savefiles.

As I never worked with Postgres OR Django (I'm working with MariaDB and Node or PHP mostly) it was all try-and-error to even get to the point that I'm at right now.

This is what I have done to this point:
- installed postgres-10, python 3.6 and virtualenv
- configured postgres, created database, added the unaccent functions
- created FT_ENV with "python3 -m virtualenv FT_ENV" in /home/fifatracker/
- cloned git repository
- sourced ~/FT_ENV/bin/activate 
- did the three migrations players 0001, 0002 -fake and migrate as defined in your README
- added the nations19 and playernames19  AND nations20 and playernames20 tables using your csv templates
- created an .env settings file with SECRET and Database-Settings (in your README you're still referencing a secret_settings.py)
- started the server

At this stage, I was able to connect to the frontend but couldn't register a new user since the `accounts_profile` Table did not exist. So I was fiddling around and got it working by using 

- python manage.py makemigrations
- python manage.py migrate
**(I expect this is where I fucked something up)**

After that I was able to register a user, I was getting an AttributeError but the auth_ and accounts_ Entries were created anyways, I activated my user by setting `is_superuser`, `is_staff` and `is_activated` in the `auth_users` to true and was able to log in.

Then I uploaded a **FIFA 19** Career Save using the upload form.

- Extracting the FIle works
- Extracting the CSV files work
- Calculating Values and so on is working

But when it comes to reading the data from the extracted csv-files into postgres I get the following error in the runserver output:

> Exception while running run() in 'scripts.import_career_data'
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/fifatracker/FT_ENV/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/fifatracker/FT_ENV/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/fifatracker/FT_ENV/lib/python3.6/site-packages/django_extensions/management/email_notifications.py", line 65, in run_from_argv
    super(EmailNotificationCommand, self).run_from_argv(argv)
  File "/home/fifatracker/FT_ENV/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/fifatracker/FT_ENV/lib/python3.6/site-packages/django_extensions/management/email_notifications.py", line 77, in execute
    super(EmailNotificationCommand, self).execute(*args, **options)
  File "/home/fifatracker/FT_ENV/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/fifatracker/FT_ENV/lib/python3.6/site-packages/django_extensions/management/utils.py", line 59, in inner
    ret = func(self, *args, **kwargs)
  File "/home/fifatracker/FT_ENV/lib/python3.6/site-packages/django_extensions/management/commands/runscript.py", line 242, in handle
    run_script(mod, *script_args)
  File "/home/fifatracker/FT_ENV/lib/python3.6/site-packages/django_extensions/management/commands/runscript.py", line 148, in run_script
    mod.run(*script_args)
  File "/mnt/netshare/home/fifatracker/netshare/FIFA-Tracker/FIFATracker/scripts/import_career_data.py", line 25, in run
    file=f
psycopg2.errors.ForeignKeyViolation: insert or update on table "datausersplayers19" violates foreign key constraint "datausersplayers19_lastnameid_fb5b3bf2_fk_dataplaye"
DETAIL:  Key (lastnameid)=(34001) is not present in table "dataplayernames19".

The `core_careersavefilemodel` does output a success however.
There is also a lack of errors in the `FIFA_TRACKER_LOGS.log`:

> 2020-01-30 16:05:29,210 INFO Unpacking database from career file.
2020-01-30 16:05:29,528 INFO Exporting data from FIFA database to csv files.
2020-01-30 16:05:29,532 INFO Tables processed in 0.001s.
2020-01-30 16:05:29,537 INFO Files created in 0.00448s.
2020-01-30 16:05:35,515 INFO Tables processed in 5.977s.
2020-01-30 16:05:35,606 INFO Files created in 0.09126s.
2020-01-30 16:05:35,607 INFO DB to CSV in 6.077s.
2020-01-30 16:05:35,714 INFO Rest to CSV in 0.107s.
2020-01-30 16:05:35,722 INFO Calculating Players Values and Teams Ratings
2020-01-30 16:05:37,848 INFO CalculateValues in 2.125s.
2020-01-30 16:05:37,849 INFO Importing data to FIFA Tracker database.
2020-01-30 16:05:40,394 INFO Tables imported in 2.444s.
2020-01-30 16:05:40,394 INFO Completed in 11.233s

Could you tell me what I did wrong?
If I'd have to guess it's because there are no nameids > 29447 in my `dataplayernames19` postgres-table but there are entries with either firstname, lastname and jersey id > 29447 in the `players.csv`. But I'm at a loss what to do here.

As the exporting from csv and all the calculations in your `process_file_utils` seem to be working no problem I'm currently inclined to just stop your script at that point, adding more tables to the `SUPPORTED_TABLES` const and just read them into a mariadb to work with the tables that way but getting this working would probably be a very good way to get into Django and Postgres so I'd really like to get it working so I can play around with this project.

Kind Regards

**Comment by qhash1** [comment]
Forgot to attach this:

[tablestructure.sql.txt](https://github.com/xAranaktu/FIFA-Tracker/files/4134984/tablestructure.sql.txt)

**Comment by xAranaktu** [comment]
Migrations in repo are not up to date.
Fix:
1. open `FIFA-Tracker\FIFATracker\players\models.py` in your IDE
2. Find `DataUsersPlayers19` class
3. uncomment firstnameid, lastnameid, playerjerseynameid, commonnameid
4. comment firstname, lastname, playerjerseyname, commonname
![](https://i.imgur.com/Qjt4HnQ.png)
5. Make migrations and migrate
```sh
python manage.py makemigrations
python manage.py migrate
```
![](https://i.imgur.com/eLhLOyJ.png)
6. again open `FIFA-Tracker\FIFATracker\players\models.py` file
7. Find `DataUsersPlayers19` class and restore it to the original state (comment firstnameid, lastnameid, playerjerseynameid, commonnameid & uncomment firstname, lastname, playerjerseyname, commonname)
![](https://i.imgur.com/LkmtLW6.png)
8. Make migrations and **fake** migrate
```sh
python manage.py makemigrations
python manage.py migrate --fake
```
![](https://i.imgur.com/wZLqmAw.png)
9. Run server and upload your CM save (Make sure to switch to FIFA 19 before you upload).
![](https://i.imgur.com/uO5uSj1.png)

**Comment by qhash1** [comment]
Great! All working now, thanks :)
